# main.pyを実行する際のパラメータ設定

# 実行モードを指定
mode_list: [
    simulation,
    # assimilation,
    # optimize,
]

# 実行したいconditionファイルを指定
cond_list: [
  # 5_05_mod_termination_conds,
  # 5_06_mod_termination_conds2,
  5_08_mod_logging2
]

# パラメータ最適化のパラメータ
opt_params: {
  num_processes: 4,
  num_trials: 100,
}